/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Login;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author pratiksha shetty
 */
public class Defaulter extends javax.swing.JFrame {

    /**
     * Creates new form Defaulter
     */
    public Defaulter() {
        initComponents();
        Show_Student_In_Table();
    }
    int pos=0;
    public Connection getConnection()
    {
        try{
        Connection con=null;
        con = DriverManager.getConnection("jdbc:mysql://localhost/student_record","root","");
        
        return con;
        }
        catch(SQLException ex)
        {
            Logger.getLogger(Main_Window.class.getName()).log(Level.SEVERE,null,ex);

            return null;

        }       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        lbl_search = new javax.swing.JLabel();
        txt_search = new javax.swing.JTextField();
        btn_search = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable.setBorder(new javax.swing.border.MatteBorder(null));
        jTable.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NAME", "ROLL_NO", "PID_NO", "ATTENDANCE", "PERFORMANCE"
            }
        ));
        jTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 604, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(498, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        lbl_search.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lbl_search.setText("Enter any Value To be Searched :");

        txt_search.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        txt_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_searchKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_searchKeyTyped(evt);
            }
        });

        btn_search.setText("Search");
        btn_search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_searchMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(lbl_search, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(150, 150, 150)
                        .addComponent(btn_search, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(168, 168, 168))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_search)
                    .addComponent(btn_search)
                    .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(254, 254, 254)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMouseClicked

    }//GEN-LAST:event_jTableMouseClicked

    private void txt_searchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchKeyPressed

    }//GEN-LAST:event_txt_searchKeyPressed

    private void txt_searchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchKeyTyped
        if(!"".equals(txt_search.getText())){
            String word=txt_search.getText();
            Connection con=getConnection();
            try {
                PreparedStatement ps=con.prepareStatement("SELECT * FROM students WHERE Name=? OR Roll_no=? OR PID=? OR Attendance=? OR Performance=?");
                ps.setString(1,word);
                ps.setString(2,word);
                ps.setString(3,word);
                ps.setString(4,word);
                ps.setString(5,word);
                ResultSet rs;
                rs = ps.executeQuery();
                DefaultTableModel model1=(DefaultTableModel)jTable.getModel();

                model1.setRowCount(0);

                Object[] row1 = new Object[5];
                while(rs.next())
                {
                    row1[0]=rs.getString("Name");
                    row1[1]=rs.getInt("Roll_no");
                    row1[2]=rs.getInt("PID");
                    row1[3]=rs.getFloat("Attendance");
                    row1[4]=rs.getFloat("Performance");
                    pos=(rs.getInt("id"))-1;
                    model1.addRow(row1);

                }
               
           
            }
            catch (SQLException ex) {
                Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
            }}
            else{
                Show_Student_In_Table();
            }
    }//GEN-LAST:event_txt_searchKeyTyped

    private void btn_searchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_searchMouseClicked
        if(!"".equals(txt_search.getText())){
            String word=txt_search.getText();
            Connection con=getConnection();
            try {
                PreparedStatement ps=con.prepareStatement("SELECT * FROM students WHERE Name=? OR Roll_no=? OR PID=? OR Attendance=? OR Performance=?");
                ps.setString(1,word);
                ps.setString(2,word);
                ps.setString(3,word);
                ps.setString(4,word);
                ps.setString(5,word);
                ResultSet rs;
                rs = ps.executeQuery();
                DefaultTableModel model1=(DefaultTableModel)jTable.getModel();

                model1.setRowCount(0);

                Object[] row1 = new Object[5];
                while(rs.next())
                {
                    row1[0]=rs.getString("Name");
                    row1[1]=rs.getInt("Roll_no");
                    row1[2]=rs.getInt("PID");
                    row1[3]=rs.getFloat("Attendance");
                    row1[4]=rs.getFloat("Performance");
                    pos=(rs.getInt("id"))-1;
                    model1.addRow(row1);

                }
                
               
            }
            catch (SQLException ex) {
                Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
            }}
            else{
                Show_Student_In_Table();
            }

    }//GEN-LAST:event_btn_searchMouseClicked

    public ArrayList <student_record> getStudentList()
    {
            ArrayList <student_record> studentList = new ArrayList <student_record>();
            Connection con=getConnection();
            String query="SELECT * FROM student_record.students WHERE Attendance<=75";
            
            Statement st;
            ResultSet rs;
                    try {

            st=con.createStatement();
            rs=st.executeQuery(query); 
            student_record student;
            
            while(rs.next())
            {
                student=new student_record(rs.getBytes("image"),rs.getString("name"),rs.getInt("roll_no"),rs.getInt("pid"),Float.parseFloat(rs.getString("Attendance")),Float.parseFloat(rs.getString("performance"))
                );
                studentList.add(student);
                
            }
                    
                    } catch (SQLException ex) {
            Logger.getLogger(Main_Window.class.getName()).log(Level.SEVERE, null, ex);
        }
                    return studentList;
        
    }
    
    public void Show_Student_In_Table()
    {
        ArrayList <student_record> list;
        list = getStudentList();
        DefaultTableModel model=(DefaultTableModel)jTable.getModel();
        
        model.setRowCount(0);
        
        Object[] row = new Object[5];
        for(int i= 0;i<list.size();i++)
        {
            row[0]=list.get(i).getName();
            row[1]=list.get(i).getrn();
            row[2]=list.get(i).getpid();
            row[3]=list.get(i).getatt();
            row[4]=list.get(i).getperf();
        
            model.addRow(row);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Defaulter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Defaulter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Defaulter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Defaulter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Defaulter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_search;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable;
    private javax.swing.JLabel lbl_search;
    private javax.swing.JTextField txt_search;
    // End of variables declaration//GEN-END:variables
}
